# fly.toml app configuration file generated for gamertalk on 2023-11-11T11:54:46+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "gamertalk"
primary_region = "nrt"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
